catalog/urls.py
from django.urls import path, include
from . import views

app_name = 'cron'

urlpatterns = [
	path('accounts/', include('django.contrib.auth.urls')),
	path('<int:enabled>/',views.index, name='index'),
	path('',views.main, name='main'),
	path('submit',views.submit, name='submit'),
	path('login',views.login, name='login'),
	path('trylogin', views.tryLogin, name='tryLogin'),
    path('tryregister""', views.tryRegister, name='tryRegister'),
    path('register', views.register, name='register'),
	path('logout', views.logout, name='logout')
]

interaktive_website/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

urlpatterns += [
    path('catalog/', include('catalog.urls')),
]

urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/0', permanent=True)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models

class Benutzer(models.Model):
    username = models.CharField(max_length=15)
    password = models.CharField(max_length=30)

class Infos(models.Model):
    Titel = models.CharField(max_length=20)
    UrlAdresse = models.CharField(max_length=255)
    Benutzername = models.CharField(max_length=15)
    Passwort = models.CharField(max_length=30)
    Benutzerdefiniert = models.BooleanField()
    Hours = models.IntegerField()
    Hours2 = models.IntegerField()
    Minutes = models.IntegerField()
    Minutes2 = models.IntegerField()
    FehlschlagAlert = models.BooleanField()
    ErfolgNachFehlschlagAlert = models.BooleanField()
    ZuVielFehlschlaege = models.BooleanField()
    AntwortenSpeichern = models.BooleanField()
    MyNumber = models.IntegerField()
    MyNumber2 = models.IntegerField()

catalog/views.py
from django.contrib.auth import authenticate
from django.shortcuts import render
from catalog.models import Infos
from catalog.models import Benutzer
from django.urls import reverse
from django.http import HttpResponseRedirect

num_visits = 0


def main(request):
    return HttpResponseRedirect(reverse("cron:index", args=(0,)))


def login(request, Account=1):
    return render(request, 'login.html', {'Account': Account})


def register(request, Account=0):
    return render(request, 'login.html', {'Account': Account})


def tryLogin(request):
    loginName = request.POST['login_name']
    loginPassword = request.POST['login_password']
    user = authenticate(username=loginName, password=loginPassword)
    if user is not None:
        request.session['LoggedIn'] = True
        request.session['username'] = loginName
        request.session.set_expiry(0)
        return HttpResponseRedirect(reverse('cron:index', args=(0,)))
    else:
            return render(request, 'login.html', {
                'warnung_nachricht': "Dein Passwort oder Benutzername sind nicht korrekt",
                'Account': 1,
                'login_name': loginName,
                'login_password': loginPassword
            })


def tryRegister(request):
    loginName = request.POST.get('login_name')
    loginPassword = request.POST.get('login_password')
    try:
        benutzer_data = Benutzer.objects.get(username=loginName)
    except(KeyError, Benutzer.DoesNotExist):
        eingabe = Benutzer(username=loginName, password=loginPassword)
        eingabe.save()
        return HttpResponseRedirect(reverse('cron:login'))
    else:
        return render(request, 'login.html', {
            'warnung_nachricht': "Diese Benutzername existiert bereits",
            'Account': 0,
            'login_name': loginName,
            'login_password': loginPassword
        })


def logout(request):
    if request.session.get('LoggedIn', False):
        request.session.set_expiry(1)
        return render(request, 'login.html', {

        })



def index(request, enabled=0):
    global num_visits
    num_visits = num_visits + 1
    loginName = request.session.get('username')
    if request.session.get('LoggedIn', False):
        return render(request, 'index.html', {
            "enabled": enabled,
            "error": "",
            'login_name': loginName,
            'num_visits': num_visits
        })
    else:
        return render(request, 'login.html', {
            'warnung_nachricht': "Bitte einloggen",
            'Account': 1
        })


def stringToBoolean(string):
    if string == "on":
        return True
    else:
        return False


def login(request, enabled=0):
    if request.session.get('LoggedIn', False):
        return render(request, 'index.html', {
            "enabled": enabled,
            "error": ""
        })
    else:
        return render(request, 'login.html', {
            'warning_nachricht': "Können Sie sich bitte einloggen",
            'Account': 1
        })


def submit(request, enabled=0):
    if request.session.get('LoggedIn', False):
        titel = request.POST.get('titel')
        url = request.POST.get('url')
        myNumber2 = request.POST.get('myNumber2')
        myNumber = request.POST.get('myNumber')
        hours = request.POST.get('hours')
        benutzerdefiniert = False
        requiredhttp = bool(enabled)
        Wahl1 = False
        Wahl2 = False
        Wahl3 = False
        Wahl4 = False
        hours2 = request.POST.get('hours2')
        minutes = request.POST.get('minutes')
        minutes2 = request.POST.get('minutes2')
        fehlschlagAlert = stringToBoolean(request.POST.get("fehlschlagAlert"))
        erfolgNachFehlschlagAlert = stringToBoolean(request.POST.get("erfolgNachFehlschlagAlert"))
        ausgewaehltewahl = request.POST.get("a")
        if ausgewaehltewahl == "Wahl1":
            Wahl1 = True
            myNumber2 = int(request.POST['myNumber2'])
        elif ausgewaehltewahl == "Wahl2":
            Wahl2 = True
            hours = int(request.POST['hours'])
            minutes = int(request.POST['minutes'])
        elif ausgewaehltewahl == "Wahl3":
            Wahl3 = True
            myNumber = int(request.POST['myNumber'])
            hours2 = int(request.POST['hours2'])
            minutes2 = int(request.POST['minutes2'])
        else:
            Wahl4 = True
            benutzerdefiniert = True
        zuVielFehlschlaege = stringToBoolean(request.POST.get("zuVielFehlschlaege"))
        antwortenSpeichern = stringToBoolean(request.POST.get("antwortenSpeichern"))
        if requiredhttp:
            benutzername = request.POST.get('benutzername')
            passwort = request.POST.get('passwort')
            try:
                benutzer_data = Benutzer.objects.get(username=benutzername)
            except(KeyError, Benutzer.DoesNotExist):
                return render(request, 'index.html', {
                    "enabled": enabled,
                    "warnung": "Sie können nicht ein Cron Job für einen anderen Benutzer machen"
                })
            else:
                richtige_password = benutzer_data.password
                if richtige_password != passwort:
                    return render(request, 'index.html', {
                        "enabled": enabled,
                        "warning": "Sie können nicht ein Cron Job für einen anderen Benutzer machen"
                    })
        else:
            benutzername = ""
            passwort = ""
        eingabe = Infos(Titel=titel, UrlAdresse=url, Benutzername=benutzername,
                        Passwort=passwort, Hours=hours, Hours2=hours2, Minutes=minutes,
                        Minutes2=minutes2, FehlschlagAlert=fehlschlagAlert,
                        ErfolgNachFehlschlagAlert=erfolgNachFehlschlagAlert,
                        ZuVielFehlschlaege=zuVielFehlschlaege, AntwortenSpeichern=antwortenSpeichern,
                        MyNumber=myNumber, MyNumber2=myNumber2, Benutzerdefiniert=benutzerdefiniert)
        eingabe.save()
        return render(request, 'submit.html', {
            "Titel": titel,
            "Wahl1": Wahl1,
            "Wahl2": Wahl2,
            "Wahl3": Wahl3,
            "Wahl4": Wahl4,
            "UrlAdresse": url,
            "Benutzername": benutzername,
            "Passwort": passwort,
            "Hours": hours,
            "Hours2": hours2,
            "Minutes": minutes,
            "Minutes2": minutes2,
            "FehlschlagAlert": fehlschlagAlert,
            "ErfolgNachFehlschlagAlert": erfolgNachFehlschlagAlert,
            "ZuVielFehlschlaege": zuVielFehlschlaege,
            "AntwortenSpeichern": antwortenSpeichern,
            "MyNumber": myNumber,
            "MyNumber2": myNumber2,
            "Benutzerdefiniert": benutzerdefiniert})
    else:
        return render(request, 'login.html', {
            'warning_nachricht': "Bitte Einloggen",
            'Account': 1
        })

catalog/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cron-Job</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<div class="lefter">
 <div class="menu-bar">
        <h4>Du bist als {{login_name}} angemeldet. Du hast {{num_visits}} Mal diese Website besucht. Willst du dich ausloggen? <a href="{% url 'cron:logout' %}">Logout</a></h4>
    </div>

{% if enabled == 0 %}
<h1>Cron-Job erstellen</h1>
<h4>Titel, Adresse</h4>

<form action="{% url 'cron:submit' %}" method="post">{% csrf_token %}
    <div class=border1>
        <label class="placeholder">
            <input type="text" name="titel" placeholder="Titel"><br>
        </label>
        <label>
            <input type="text" name="url" value="http://"><br>
        </label>
    </div>
    <label>
        <a class="link" {% if enabled == 0 %} href="{% url 'cron:index' 1 %}" {% else %}
           href="{% url 'cron:index' 0 %}" {% endif %}>{% if enabled == 1 %}X{% endif %}</a><a>Erfordert
        HTTP-Authentifizierung</a>
    </label>
    <div class=border2>
        <label>
            Benutzername <input type="text" name="benutzername" required {% if enabled == 0 %} disabled {% endif %}>
            Passwort <input type="password" name="passwort" required {% if enabled == 0 %}disabled{% endif %}><br>
        </label>
    </div>
    <h4>Ausführung</h4>
    <div class=border>
        <label>
            <input type="radio" name="a" value="Wahl1">Alle <input type="number" name="myNumber2"
                                                                   value="15">Minute(n)<br>
        </label>
        <label>
            <input type="radio" name="a" value="Wahl2">Jeden Tag um <input type="number" name="hours" value="00">:<input
                type="number" name="minutes" value="00"><br>
        </label>
        <label>
            <input type="radio" name="a" value="Wahl3">Immer am <input type="number" name="myNumber" value="1"> des
            Monats um <input type="number" name="hours2" value="00">:<input type="number" name="minutes2"
                                                                            value="00"><br>
        </label>
        <label>
            <input type="radio" name="a" value="Wahl4">Benutzerdefiniert<br>
        </label>
    </div>
    <h4>Benachrichtungen</h4>
    <div class=border3>
        <label>
            <p>Mich per E-Mail benachrichtigen bei</p>
        </label>
        <label>
            <input type="checkbox" name="fehlschlagAlert">Fehlschlag des Jobs<br>
        </label>
        <label>
            <input type="checkbox" name="erfolgNachFehlschlagAlert">erfolgreichem Abruf nach vorherigem fehlschlag<br>
        </label>
        <label>
            <input type="checkbox" name="zuVielFehlschlaege">automatischer Deaktivierung wegen zu vieler Fehlschläge<br>
        </label>
    </div>
    <h4>Allgemein</h4>
    <div class=border4>
        <label>
            <input type="checkbox" name="antwortenSpeichern">Antworten speichern<br>
        </label>
    </div>
    <h5>Mit der Erstellung des Cron-Jobs erklären Sie, dass Sie entweder der Inhaber der abzurufenden Website sind oder im
        Einverständnis des Inhabers handeln.</h5>
    <input type="submit" class="submit" value="Cron-Job erstellen">
</form>

{% else %}

    <p>Bitte anmelden: <a href="">Login</a></p>
{% endif %}
</div>
</body>
</html>

catalog/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body class="central">
    <div>
        <h1>Anmelden</h1>

        {% if warning_nachricht %}<p><strong> {{warning_nachricht}}</strong></p> {% endif %}

        <form name="forlogin" id="login" method="post" {% if Account == 1 %}action="{% url 'cron:tryLogin' %}" {% else %} action="{% url 'cron:tryRegister' %}" {% endif %}>{% csrf_token %}
            <p>Bitte fügen Sie ihre Benutzername ein (erstellen Sie zuerst einen Benutzer in Django Admin Site (login:admin und passwort:superuser)</p>
            <input type="text " id="login_name" name="login_name" value={{login_name}}>
            <p>Bitte fügen Sie ihre Passwort ein</p>
            <input type="password" id="login_password" name="login_password" value={{login_password}}>
            <input id="login_button" type="submit" value="Einloggen" >
        </form>
    </div>
</body>
</html>

catalog/templates/submit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Submit</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body class="central">
    <h2>Sie haben ein CronJob gemacht, bravo!!!</h2>
    <h4>Titel:</h4>
    <p>{{Titel}}</p>
    <h4>URL:</h4>
    <p>{{UrlAdresse}}</p>
    <h4>Zeit</h4>
    {% if Wahl4 %}
        <p>Die Zeit ist Benutzerdefiniert</p>
    {% endif %}
    {% if Wahl1 %}
            <p>Das Cron Job wird sich jede {{myNumber2}} Minute(n) wiederholen</p>
            {% endif %}
    {% if Wahl2 %}
            <p>Das Cron Job wird jeden tag um {{hours}}:{{minutes}} ausgeführt.</p>
        {% endif %}
    {% if Wahl3 %}
            <p>Das Cron Job wird immer am {{myNumber}} des Monats um {{hours2}}:{{minutes2}} ausgeführt</p>
        {% endif %}
    <h4>Fehlschlag:</h4>
    <p>{{FehlschlagAlert}}</p>
    <h4>Erfolgreich nach Fehlschlag:</h4>
    <p>{{ErfolgNachFehlschlagAlert}}</p>
    <h4>Zu viele Fehlschlaege:</h4>
    <p>{{ZuVielFehlschlaege}}</p>
    <h4>Antworten speichern:</h4>
    <p>{{AntwortenSpeichern}}</p>
</body>
</html>